version: '3.9'

services:
  bot:
    container_name: cafe_bot_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment: # <---
      TZ: 'Asia/Yekaterinburg'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cafe_bot_network

  redis:
    container_name: redis_storage
    image: redis:7-alpine # Ð˜ÑÐ¿Ð¾Ð»ÑŒÐ·ÑƒÐµÐ¼ Ð¾Ñ„Ð¸Ñ†Ð¸Ð°Ð»ÑŒÐ½Ñ‹Ð¹, Ð»ÐµÐ³ÐºÐ¸Ð¹ Ð¾Ð±Ñ€Ð°Ð·
    restart: always
    environment: # <---
      TZ: 'Asia/Yekaterinburg'
    ports:
      - "6379:6379"   # ðŸ‘ˆ Ð”Ð¾Ð±Ð°Ð²Ð»ÑÐµÐ¼ Ð¿Ñ€Ð¾Ð±Ñ€Ð¾Ñ Ð¿Ð¾Ñ€Ñ‚Ð°
    volumes:
      - redis_data:/data # Ð¡Ð¾Ñ…Ñ€Ð°Ð½ÑÐµÐ¼ Ð´Ð°Ð½Ð½Ñ‹Ðµ Redis Ð¼ÐµÐ¶Ð´Ñƒ Ð¿ÐµÑ€ÐµÐ·Ð°Ð¿ÑƒÑÐºÐ°Ð¼Ð¸
    networks:
      - cafe_bot_network
  db:
    container_name: pg_db
    image: postgres:14-alpine
    restart: always
    environment:
      TZ: 'Asia/Yekaterinburg'
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/tables.sql:/docker-entrypoint-initdb.d/tables.sql
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cafe_bot_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      TZ: 'Asia/Yekaterinburg'
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '5053:80'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cafe_bot_network

  cloudflare_tunnel:
    container_name: cloudflare_tunnel_cb
    image: cloudflare/cloudflared:latest
    restart: always
    environment:
      TZ: 'Asia/Yekaterinburg'
      # ÐŸÐµÑ€ÐµÐ´Ð°ÐµÐ¼ Ñ‚Ð¾ÐºÐµÐ½ ÐºÐ°Ðº Ð¿ÐµÑ€ÐµÐ¼ÐµÐ½Ð½ÑƒÑŽ Ð¾ÐºÑ€ÑƒÐ¶ÐµÐ½Ð¸Ñ, ÐºÐ°Ðº Ð² Ð²Ð°ÑˆÐµÐ¼ Ñ€Ð°Ð±Ð¾Ñ‡ÐµÐ¼ Ð¿Ñ€Ð¸Ð¼ÐµÑ€Ðµ
      TUNNEL_TOKEN: "${CLOUDFLARE_TUNNEL_TOKEN}"
    # ÐÐ´Ð°Ð¿Ñ‚Ð¸Ñ€Ð¾Ð²Ð°Ð½Ð½Ð°Ñ Ð¿Ð¾Ð´ ÑÑ‚Ð¾Ñ‚ Ð¿Ñ€Ð¾ÐµÐºÑ‚ ÐºÐ¾Ð¼Ð°Ð½Ð´Ð°
    command: tunnel run --url http://cafe_bot_app:8010 cafe_bot.n8npblocally.xyz
    depends_on:
      bot:
        condition: service_started # Ð–Ð´ÐµÐ¼, Ð¿Ð¾ÐºÐ° ÑÐµÑ€Ð²Ð¸Ñ Ð±Ð¾Ñ‚Ð° Ð·Ð°Ð¿ÑƒÑÑ‚Ð¸Ñ‚ÑÑ
    networks:
      - cafe_bot_network

volumes:
  postgres_data:
  redis_data:

networks:
  cafe_bot_network:
    driver: bridge