version: '3.9'

services:
  bot:
    container_name: cafe_bot_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cafe_bot_network

  redis:
    container_name: redis_storage
    image: redis:7-alpine # –ò—Å–ø–æ–ª—å–∑—É–µ–º –æ—Ñ–∏—Ü–∏–∞–ª—å–Ω—ã–π, –ª–µ–≥–∫–∏–π –æ–±—Ä–∞–∑
    restart: always
    ports:
      - "6379:6379"   # üëà –î–æ–±–∞–≤–ª—è–µ–º –ø—Ä–æ–±—Ä–æ—Å –ø–æ—Ä—Ç–∞
    volumes:
      - redis_data:/data # –°–æ—Ö—Ä–∞–Ω—è–µ–º –¥–∞–Ω–Ω—ã–µ Redis –º–µ–∂–¥—É –ø–µ—Ä–µ–∑–∞–ø—É—Å–∫–∞–º–∏
    networks:
      - cafe_bot_network
  db:
    container_name: pg_db
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/tables.sql:/docker-entrypoint-initdb.d/tables.sql
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cafe_bot_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '5053:80'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cafe_bot_network

  cloudflare_tunnel:
    container_name: cloudflare_tunnel_cb
    image: cloudflare/cloudflared:latest
    restart: always
    environment:
      # –ü–µ—Ä–µ–¥–∞–µ–º —Ç–æ–∫–µ–Ω –∫–∞–∫ –ø–µ—Ä–µ–º–µ–Ω–Ω—É—é –æ–∫—Ä—É–∂–µ–Ω–∏—è, –∫–∞–∫ –≤ –≤–∞—à–µ–º —Ä–∞–±–æ—á–µ–º –ø—Ä–∏–º–µ—Ä–µ
      TUNNEL_TOKEN: "${CLOUDFLARE_TUNNEL_TOKEN}"
    # –ê–¥–∞–ø—Ç–∏—Ä–æ–≤–∞–Ω–Ω–∞—è –ø–æ–¥ —ç—Ç–æ—Ç –ø—Ä–æ–µ–∫—Ç –∫–æ–º–∞–Ω–¥–∞
    command: tunnel run --url http://bot:8010 cafe_bot.n8npblocally.xyz
    depends_on:
      bot:
        condition: service_started # –ñ–¥–µ–º, –ø–æ–∫–∞ —Å–µ—Ä–≤–∏—Å –±–æ—Ç–∞ –∑–∞–ø—É—Å—Ç–∏—Ç—Å—è
    networks:
      - cafe_bot_network

volumes:
  postgres_data:
  redis_data:

networks:
  cafe_bot_network:
    driver: bridge